// Generated by Wrangler on Mon May 13 2024 20:03:40 GMT+0800 (中国标准时间)
// by running `wrangler types`

interface Env {
	CACHE_CONTROL: "max-age=600";
	BROWSER_TIMEOUT: 30000;
	FETCH_CACHE_TTL: 300;
	BROWSER_USER_AGENT: "";
	AUTH_KEY: "";
	READER_BROWSER: Fetcher;
}
