// Generated by Wrangler on Wed May 29 2024 00:44:39 GMT+0800 (香港标准时间)
// by running `wrangler types`

interface Env {
	CACHE_CONTROL: string;
	BROWSER_TIMEOUT: number;
	FETCH_CACHE_TTL: number;
	BROWSER_USER_AGENT: string;
	SALVAGE_USER_AGENT: string;
	AUTH_KEY: string;
	READER_BROWSER: Fetcher;
}
