// Generated by Wrangler on Tue May 07 2024 12:47:33 GMT+0800 (中国标准时间)
// by running `wrangler types`

interface Env {
	CACHE_CONTROL: "max-age=600";
	BROWSER_TIMEOUT: 30000;
	FETCH_CACHE_TTL: 300;
	AUTH_KEY: "";
	READER_BROWSER: Fetcher;
}
