export enum ERROR_CODE {
  INVALID_AUTH_KEY = 1000,
	ABUSE,
	INVALID_HEADERS,
  INVALID_TARGET,
  UNSUPPORTED_CONTENT,
  INVALID_FETCH_RES,
  PAGE_SETUP_FAILED,
  SNAPSHOT_TIMEOUT,
  INVALID_SNAPSHOT,
  PARSE_FAILED,
	BROWSER_FAILED,
}
